spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 
            clientSecret: 
          google:
            client-id: 
            client-secret:
            
         
            
        
        
        
        
        
        
        
        
        
        
        
       
             
         
                     
      
      
  application:
    name: MovieToWatch            
 
  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/movietowatch1
     username: root
     password: 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true            
